### ISSUE TITLE
codec is deprecated and its use causes a error with GCC 6

### ISSUE THREAD

**Issue by awissu** [andrewrk/libgroove#126]
Hi!
To get the compile working I will add -Wno-error=deprecated-declarations.
See: https://pmbs.links2linux.de/build/Multimedia/openSUSE_Tumbleweed/x86_64/groove/_log

**Comment by andrewrk** [comment]
Looks like you're building 4.3.0, which is reasonable, but the newest code is in master branch, not released yet, and depends on updated ffmpeg instead of libav. So I believe this error is fixed in master.

**Comment by 1egoman** [comment]
@andrewrk I still have this issue on master. Running macos Sierra, with ffmpeg version `3.3.2`.

```
$ git clone https://github.com/andrewrk/libgroove
$ cd libgroove
$ mkdir build
$ cd build
$ cmake ..
Configuring libgroove version 5.0.0

Installation Summary
--------------------
* Install Directory            : /usr/local
* Build Type                   : Debug
* Build static libs            : ON
* Build example programs       : ON

System Dependencies
-------------------
* threads                      : OK
* libsoundio                   : OK
* ebur128                      : OK
* chromaprint                  : OK
* libavformat                  : OK
* libavcodec                   : OK
* libavfilter                  : OK
* libavutil                    : OK

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ryan/libgroove/build
$ make
[  2%] Building C object CMakeFiles/libgroove_shared.dir/src/file.c.o
/Users/ryan/w/1egoman/termtrack/libgroove/src/file.c:176:42: error: 'codec' is deprecated [-Werror,-Wdeprecated-declarations]
    AVCodecContext *avctx = f->audio_st->codec;
                                         ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
/Users/ryan/w/1egoman/termtrack/libgroove/src/file.c:235:72: error: 'codec' is deprecated [-Werror,-Wdeprecated-declarations]
        AVCodecContext *avctx = f->ic->streams[f->audio_stream_index]->codec;
                                                                       ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
/Users/ryan/w/1egoman/termtrack/libgroove/src/file.c:288:46: error: 'codec' is deprecated [-Werror,-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = f->audio_st->codec;
                                             ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
/Users/ryan/w/1egoman/termtrack/libgroove/src/file.c:384:45: error: 'codec' is deprecated [-Werror,-Wdeprecated-declarations]
        AVCodecContext *icodec = in_stream->codec;
                                            ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
/Users/ryan/w/1egoman/termtrack/libgroove/src/file.c:385:46: error: 'codec' is deprecated [-Werror,-Wdeprecated-declarations]
        AVCodecContext *ocodec = out_stream->codec;
                                             ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated here
    AVCodecContext *codec;
                    ^
5 errors generated.
make[2]: *** [CMakeFiles/libgroove_shared.dir/src/file.c.o] Error 1
make[1]: *** [CMakeFiles/libgroove_shared.dir/all] Error 2
make: *** [all] Error 2
```
